### ISSUE TITLE
Mobile Instrument settings clip through Modulator Settings title

### ISSUE THREAD

**Issue by wdymThisIsntAvailable** [choptop84/abyssbox-source#14]
![image](https://github.com/user-attachments/assets/d81fc16f-4d1a-47ce-89ed-673e5f44d06b)

**Comment by choptop84** [comment]
Fixed

**Comment by wdymThisIsntAvailable** [comment]
i forgot to mention, but there's also this bug that exists
![image](https://github.com/user-attachments/assets/9023e11e-1469-4003-9f11-96cdd0c32322)

**Comment by choptop84** [comment]
Ah I can probably fix that

**Comment by wdym-lmao** [comment]
And in the same screenshot, the dropdown menu next to Effects is too close to the sign box
