### ISSUE TITLE
I broke AbyssBox by editing my theme

### ISSUE THREAD

**Issue by wdymThisIsntAvailable** [choptop84/abyssbox-source#16]
I pasted this into the custom theme URL and after it refreshed it just stays black. I already tried going through older versions of my song in my browser history but it still stays black. 

:root { --page-margin: #050000; --editor-background: #000000; --hover-preview: #18006020; --playhead: black; --primary-text: #0060f0; --secondary-text: #f00030; --inverted-text: black; --text-selection: rgb(240 00 36 / 60%); --box-selection-fill: rgb(255 0 0 / 30%); --loop-accent: #8000f0; --link-accent: #0060f0; --ui-widget-background: #0c0618; --ui-widget-focus: #0c0618; --pitch-background: #0c0618; --tonic: #0060f060; --fifth-note: #f0003060; --third-note: #8000f060; --white-piano-key: #0c0618; --black-piano-key: #0060f0; --white-piano-key-text: #0060ff; --black-piano-key-text: #0c0618; --use-color-formula: false; --pitch-channel-limit: 12; --track-editor-bg-pitch: #0c0618; --track-editor-bg-pitch-dim: #000000; --track-editor-bg-noise: #18006060; --track-editor-bg-noise-dim: #000000; --track-editor-bg-mod: #60000c60; --track-editor-bg-mod-dim: #000000; --multiplicative-mod-slider: #180060; --overwriting-mod-slider: #f00030; --indicator-primary: #0000f020; --indicator-secondary: #f0000020; --select2-opt-group: #18006060; --input-box-outline: #0c0618; --mute-button-normal: #180060; --mute-button-mod: #600018; --pitch1-secondary-channel: #003c90; --pitch1-primary-channel: #0060F0; --pitch1-secondary-note: #003c90; --pitch1-primary-note: #0060f0; --pitch2-secondary-channel: #900012; --pitch2-primary-channel: #f00024; --pitch2-secondary-note: #900012; --pitch2-primary-note: #f00024; --pitch3-secondary-channel: #6000a0; --pitch3-primary-channel: #9000f0; --pitch3-secondary-note: #6000a0; --pitch3-primary-note: #6000a0; --pitch4-secondary-channel: #0078a0; --pitch4-primary-channel: #00b4f0; --pitch4-secondary-note: #0078a0; --pitch4-primary-note: #00b4f0; --pitch5-secondary-channel: #200078; --pitch5-primary-channel: #3000f0; --pitch5-secondary-note: #200078; --pitch5-primary-note: #3000f0; --pitch6-secondary-channel: #00a018; --pitch6-primary-channel: #00f024; --pitch6-secondary-note: #00a018; --pitch6-primary-note: #00f024; --pitch7-secondary-channel: #a04000; --pitch7-primary-channel: #f06000; --pitch7-secondary-note: #a04000; --pitch7-primary-note: #f06000; --pitch8-secondary-channel: #a0a000; --pitch8-primary-channel: #f0f000; --pitch8-secondary-note: #a0a000; --pitch8-primary-note: #f0f000; --pitch9-secondary-channel: #00a060; --pitch9-primary-channel: #00f090; --pitch9-secondary-note: #00a060; --pitch9-primary-note: #00f090; --pitch10-secondary-channel: #a00060; --pitch10-primary-channel: #f00090; --pitch10-secondary-note: #a00060; --pitch10-primary-note: #f00090; --pitch11-secondary-channel: #60a000; --pitch11-primary-channel: #90f000; --pitch11-secondary-note: #60a000; --pitch11-primary-note: #f00090; --pitch12-secondary-channel: #a07800; --pitch12-primary-channel: #f0b400; --pitch12-secondary-note: #a07800; --pitch12-primary-note: #f0b400; --noise1-secondary-channel: #4281FF; --noise1-primary-channel: #96b9ff; --noise1-secondary-note: #4281FF; --noise1-primary-note: #96b9ff; --noise2-secondary-channel: #7347FF; --noise2-primary-channel: #c3b0ff; --noise2-secondary-note: #7347FF; --noise2-primary-note: #c3b0ff; --noise3-secondary-channel: #9F3CBF; --noise3-primary-channel: #e29cf9; --noise3-secondary-note: #9F3CBF; --noise3-primary-note: #e29cf9; --noise4-secondary-channel: #D3326F; --noise4-primary-channel: #fb9bbf; --noise4-secondary-note: #D3326F; --noise4-primary-note: #fb9bbf; --noise5-secondary-channel: #FF2A2A; --noise5-primary-channel: #ffa2a2; --noise5-secondary-note: #FF2A2A; --noise5-primary-note: #ffa2a2; --mod1-secondary-channel: #47587a; --mod1-primary-channel: #96b9ff; --mod1-secondary-note: #47587a; --mod1-primary-note: #96b9ff; --mod2-secondary-channel: #716791; --mod2-primary-channel: #c3b0ff; --mod2-secondary-note: #716791; --mod2-primary-note: #c3b0ff; --mod3-secondary-channel: #6f4c7b; --mod3-primary-channel: #e29cf9; --mod3-secondary-note: #6f4c7b; --mod3-primary-note: #e29cf9; --mod4-secondary-channel: #9e6279; --mod4-primary-channel: #fb9bbf; --mod4-secondary-note: #9e6279; --mod4-primary-note: #fb9bbf; --mod-label-primary: #0c0618; --mod-label-secondary-text: #f00030; --mod-label-primary-text: #0060f0; --disabled-note-primary: #c9c9c9; --disabled-note-secondary: #616161; --note-flash: #ffffff; --note-flash-secondary: #0c0618; --pitch2-background: #24006060; --pitch9-background: #24006060; --song-player-margin: #000000; --progress-bar: #f0002460; }

**Comment by wdymThisIsntAvailable** [comment]
fixed by refreshing cookies

**Comment by choptop84** [comment]
You probably forgot a ; somewhere, causing an issue

**Comment by choptop84** [comment]
btw, if the theme doesn't work, then everything will refuse to have visuals, its just how it is unfortunately

**Comment by wdymThisIsntAvailable** [comment]
I just checked if there were any missing semicolons, turns out there wasn't any. I think changing the pitch channel limit to 12 is why the website goes black.

**Comment by choptop84** [comment]
Ah that makes sense, the maximum is already 12 and going higher is impossible so you don't need it
