### ISSUE TITLE
Unison doesn't work on FM

### ISSUE THREAD

**Issue by wdymThisIsntAvailable** [choptop84/abyssbox-source#17]
Either unison wasn't meant to be with FM or you made an error in coding.

**Comment by choptop84** [comment]
I already fixed this for 1.5 so it won't be an issue soon

**Comment by wdym-lmao** [comment]
Pasting FM instruments with custom unison resets to the default 'none' unison. This is a bug related to this.

**Comment by choptop84** [comment]
Unison wasn't ever meant to be on FM, I made a mistake

**Comment by wdym-lmao** [comment]
It also doesn't work on supersaws

**Comment by choptop84** [comment]
This issue was caused by a misspelling I made in the code, I never actually programmed unison into those instruments

**Comment by wdym-lmao** [comment]
Maybe you could keep the unison in both instruments?

**Comment by choptop84** [comment]
Supersaw and FM? The code literally doesn't exist for it to even do anything so keeping the dropdown doesn't benefit anybody. Besides I don't have the desire to add unison to supersaw and fm anyways.
