### ISSUE TITLE
SVGs for mobile buttons

### ISSUE THREAD

**Issue by wdym-lmao** [choptop84/abyssbox-source#18]
i dont know how to make pull requests so i'll just submit this issue and see if you'll add this.
the svg buttons are for every theme that doesn't use a pixel art-style.
if requested, there will be a follow-up comment for other buttons that will be vectorized.

![looponselectedbarMobile](https://github.com/user-attachments/assets/c2629047-64de-4cef-84b6-0f1094aaac99)
![movenotesdown](https://github.com/user-attachments/assets/1459527c-ba44-48f6-8f53-74b7c490c009)
![movenotesupMobile](https://github.com/user-attachments/assets/65fb028a-4483-4373-8792-2c3ffd2d588b)
![duplicateMobile](https://github.com/user-attachments/assets/5dc42433-0cfc-4db9-99c0-eb0f6e662373)
![selectallMobile](https://github.com/user-attachments/assets/fe8af7a1-ddbc-4071-98d7-8df9ddeaf0ba)
![deleteselectedchannelMobile](https://github.com/user-attachments/assets/0ab5f8b4-033d-401b-adc4-dc0142bdbd8a)
![insertchannelbelowMobile](https://github.com/user-attachments/assets/e6fde8f1-e1e1-4cc2-b61e-c8c8ff244da7)
![pasteMobile](https://github.com/user-attachments/assets/5352044f-6d95-44e6-aaa9-6aaa53d20e48)
![copyMobile](https://github.com/user-attachments/assets/d2d19ffd-e718-4ec5-af75-52b9ab46f5cd)
![redoMobile](https://github.com/user-attachments/assets/fba87bfc-6c8d-41a6-97f8-063a96ae4bd2)
![undoMobile](https://github.com/user-attachments/assets/25aa7019-7e43-4a8c-b86b-21e34471aaca)

**Comment by choptop84** [comment]
All right, I'll add these, what name do I put in the credits for making these?

**Comment by choptop84** [comment]
wrong button

**Comment by wdym-lmao** [comment]
> All right, I'll add these, what name do I put in the credits for making these?
just put "wdymLmao_" in the credits

**Comment by wdym-lmao** [comment]
for the bottom left

![bottomLeft1](https://github.com/user-attachments/assets/746879c9-60b2-4532-874d-435169bfb9b1)
![bottomLeft2](https://github.com/user-attachments/assets/fd49d67a-6a31-4a5b-a040-1ba1eb76127c)
![bottomLeft3](https://github.com/user-attachments/assets/aec7f5cd-98e0-4b43-a9e6-ff8145f2edd0)

**Comment by choptop84** [comment]
I already did those

**Comment by wdym-lmao** [comment]
the high quality ones correct?

**Comment by choptop84** [comment]
yeah

**Comment by wdym-lmao** [comment]
is it drastically different than the ones i'm proposing?

**Comment by choptop84** [comment]
I mean they're already in the mod so you can look for yourself

**Comment by wdym-lmao** [comment]
they're pixelated

**Comment by wdym-lmao** [comment]
what im proposing are for the non-retro themes

**Comment by choptop84** [comment]
![image](https://github.com/user-attachments/assets/3e09aeb5-2c7e-49c7-9686-2d525d538df0)
![image](https://github.com/user-attachments/assets/5d1a6f02-8056-4bd1-907a-3f7819a027bf)
![image](https://github.com/user-attachments/assets/3958e596-eeba-47b5-a843-15b1c7b0f66d)
Indeed they are for non-retro themes

**Comment by wdym-lmao** [comment]
i guess it'll do

**Comment by wdym-lmao** [comment]
Updated designs for _Insert Channel Below_, _Duplicate Selected Pattern_, and _Select All_
![insertchannelbelowMobile](https://github.com/user-attachments/assets/17986ace-9226-4050-9efb-418d2c5ce09c)
![duplicateMobile](https://github.com/user-attachments/assets/52b4c4cb-d756-4600-88e0-ca762520f103)
![selectallMobile](https://github.com/user-attachments/assets/e220c577-2e98-47bb-91a7-760c331e14f9)
