### ISSUE TITLE
Mysterious 5

### ISSUE THREAD

**Issue by wdym-lmao** [choptop84/abyssbox-source#19]
this wasnt here before
i already refreshed and its still there
![image](https://github.com/user-attachments/assets/a9112a80-8ec8-4213-b08f-88b4a7fc95d2)

**Comment by choptop84** [comment]
It's called "Selection Counter", it gives you the total channels you have selected currently. So this is intentional. Though I should probably give it a title to prevent people from being confused about it.

**Comment by wdym-lmao** [comment]
> It's called "Selection Counter", it gives you the total channels you have selected currently. So this is intentional. Though I should probably give it a title to prevent people from being confused about it.

A recommendation to the selection counter, try making the font bolder to fit with my proposed icons.

**Comment by choptop84** [comment]
Sure why not

**Comment by wdym-lmao** [comment]
something else to note
![image](https://github.com/user-attachments/assets/152ecf65-5f5f-4c05-9d3c-a3195316f222)
![image](https://github.com/user-attachments/assets/8d5fc54c-9573-44ff-b37c-4e40b8f33a9b)

**Comment by choptop84** [comment]
What am I looking at here

**Comment by choptop84** [comment]
Yeah what about it

**Comment by wdym-lmao** [comment]
it doesnt fit with the theme, it shouldnt exist

**Comment by choptop84** [comment]
The background is there because it would look terrible if it wasn't there. (as seen below)
![image](https://github.com/user-attachments/assets/7832af34-e49f-4ed8-ad76-76d0384dc29d)

**Comment by wdym-lmao** [comment]
> The background is there because it would look terrible if it wasn't there. (as seen below) ![image](https://private-user-images.githubusercontent.com/88958828/362107140-7832af34-e49f-4ed8-ad76-76d0384dc29d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTU0NzksIm5iZiI6MTcyNDgxNTE3OSwicGF0aCI6Ii84ODk1ODgyOC8zNjIxMDcxNDAtNzgzMmFmMzQtZTQ5Zi00ZWQ4LWFkNzYtNzZkMDM4NGRjMjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYWI3NjFjYjU2YzBmMDc5ZGRkODA4YmUzOTM4YmYyMTE5MjNhODgyZDdmNWUwMGM0ZWU3ZWNlNWVjZjI2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2j42ASFJQxaEHKD5RQ2ZyiQ4Bv2czxuzQ_rUDB5F3U)

what about making it transparent?
