### ISSUE TITLE
Annoying scroll issue when description is turned off

### ISSUE THREAD

**Issue by bsoap-cat** [choptop84/abyssbox-source#3]
There's a pair of lines that exists below the song player when the description is turned off.

**Comment by choptop84** [comment]
do those lines happen to be?
![image](https://github.com/choptop84/abyssbox-source/assets/88958828/67244e2d-5b27-453b-b9ba-d10e5362e0f7)

**Comment by choptop84** [comment]
Oh in the song player...

**Comment by bsoap-cat** [comment]
yea it's in the song player

**Comment by choptop84** [comment]
Could you post a screenshot? I'm incapable of recreating this on firefox.

**Comment by bsoap-cat** [comment]
![image](https://github.com/choptop84/abyssbox-source/assets/127647009/7d905ad2-510d-486a-89e4-1a5c11f85bde)
here's the issue

**Comment by choptop84** [comment]
Ohh you meant the track editor!

**Comment by choptop84** [comment]
Hold on

**Comment by bsoap-cat** [comment]
no like the whole page

**Comment by choptop84** [comment]
Yeah that's because Frutiger Aero has a border around the song editor

**Comment by choptop84** [comment]
if you scroll up the line won't show itself. and the one on the top isn't as easy to spot

**Comment by bsoap-cat** [comment]
![image](https://github.com/choptop84/abyssbox-source/assets/127647009/074e90c5-7fe0-4802-8a9b-5ead08da56f7)
closer look at the line

**Comment by choptop84** [comment]
Are you referring to the darker of the two lines?

**Comment by bsoap-cat** [comment]
both lines aren't meant to be on the page

**Comment by choptop84** [comment]
The issue likely lies in the theme itself due to the border existing. I could set it up so then there's no padding on any sides of the page when there isn't a description or set it so then the border hides itself in the same way.

**Comment by bsoap-cat** [comment]
List of themes with scroll issue:
Abyssbox Classic
Abyssbox Light
Undertale
Scratch
Scratch Addons
Windows XP
Fruitiger Aero
Glyde
Forest 2
Nebula 2
AWeebyssBox

**Comment by choptop84** [comment]
Fixed this
