### ISSUE TITLE
"Abyssbox 1.2> Presets"

### ISSUE THREAD

**Issue by wdymThisIsntAvailable** [choptop84/abyssbox-source#6]
looks unintended
![image](https://github.com/choptop84/abyssbox-source/assets/127647009/fe8cbce9-c33b-46a4-8a41-77bb50b3c991)

**Comment by choptop84** [comment]
It's intentional, its to show the difference between the presets added in AbyssBox 1.2 and prior, while the other one is to show the AbyssBox 1.3 and onwards presets, don't ask me why I did that I forgot myself

**Comment by wdymThisIsntAvailable** [comment]
> …its to show the difference between the presets added in AbyssBox 1.2 and prior, while the other one is to show the AbyssBox 1.3 and onwards presets.

Then shouldn't "AbyssBox 1.2> Presets" be "AbyssBox <1.2 Presets"? If that's the case, then "Abyssbox 1.3 Presets" should be named "Abyssbox 1.3> Presets".

**Comment by choptop84** [comment]
No, in this case AbyssBox 1.3 Presets would be renamed to "AbyssBox 1.3+" or "AbyssBox 1.2<" presets. Plus "AbyssBox <1.2" and "AbyssBox 1.2>" is literally the same thing.

**Comment by choptop84** [comment]
I changed it to be "AbyssBox 0.8 to 1.2 Presets" and "AbyssBox 1.3+ Presets" so now this isn't an issue anymore
