### ISSUE TITLE
Add blurry and delayed cursor to "2012 Video Tutorial" theme

### ISSUE THREAD

**Issue by wdym-lmao** [choptop84/abyssbox-source#7]

**Comment by choptop84** [comment]
Looking into this, its not possible I don't believe.

**Comment by wdym-lmao** [comment]
> Looking into this, its not possible I don't believe.
is it the delay that's impossible, or the blurred cursor? i'm not the smartest, but maybe you could just use a jpg of a cursor that looks blurry.

**Comment by choptop84** [comment]
They delay is impossible, the blurry cursor is but its not really worth it of the delay isn't possible

**Comment by wdym-lmao** [comment]
> They delay is impossible, the blurry cursor is but its not really worth it of the delay isn't possible

Understood. So it'll only be the blurry cursor that will be added, correct?

**Comment by choptop84** [comment]
Nah I just don't feel like doing it
